#!/usr/bin/php
<?php

require_once 'Classes/Craod/Api/Core/Bootstrap.php';

use Craod\Api\Core\Bootstrap;
use Craod\Api\Cli\Cli;

Bootstrap::initializeClassLoader();
Bootstrap::loadDependencyInjector();
Bootstrap::loadConfiguration();
Bootstrap::initializeCache();
Bootstrap::initializeDatabase();
Bootstrap::run(Cli::class);