#!/usr/bin/php
<?php

require_once 'Classes/Craod/Api/Core/Bootstrap.php';

use Craod\Api\Core\Bootstrap;
use Craod\Api\Cli\Cli;

Bootstrap::initialize([
	Bootstrap::CACHE,
	Bootstrap::CONFIGURATION,
	Bootstrap::DATABASE
]);

Bootstrap::run(Cli::class);