Craod:
  Api:
    cache:
      disable: true
    rest:
      settings:
        mode: 'staging'
        debug: false
        exposed:
          context: 'staging'
          storage:
            location: 'https://craod-public.s3.amazonaws.com/staging'
    cli:
      # Fixtures should only be available in the development and staging environments
      commands:
        - 'Craod\Api\Cli\Command\Fixture\UpCommand'
        - 'Craod\Api\Cli\Command\Fixture\DownCommand'
        - 'Craod\Api\Cli\Command\Fixture\ListCommand'
      fixtures:
        user: 'Craod\Api\Cli\Fixture\UserFixture'