Craod:
  Api:
    database:
      settings:
        dbname: 'craod'
        user: 'craod'
        password: '123'
        host: 'localhost'
        port: 5432
        driver: 'pdo_pgsql'
    mail:
      settings:
        Host: 'smtp.gmail.com'
        SMTPAuth: true
        Username: 'donotreply@craod.com'
        Password: 'nJWy&sU\RZeS+5Gb'
        SMTPSecure: 'ssl'
        Port: 465
    search:
      index: 'craod'
      settings:
        number_of_shards: 1
        number_of_replicas: 1
    doctrine:
      types:
        jsonb: 'Boldtrn\JsonbBundle\Types\JsonbArrayType'
        password: 'Cpliakas\Password\Doctrine\PasswordType'
      functions:
        string:
          cast: 'Oro\ORM\Query\AST\Functions\Cast'
          get_json_field: 'Opsway\Doctrine\ORM\Query\AST\Functions\GetJsonField'
    annotations:
      settings:
        debug: true
    user:
      onlineThreshold: '-5 minutes'
    storage:
      settings:
        buckets:
          public: 'craod-public'
          protected: 'craod-content'
        endpoint: 's3.amazonaws.com'
        accessKey: 'AKIAIWM4NXNCSMZIZAPQ'
        secretKey: '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'
    rest:
      settings:
        debug: false
    cli:
      commands:
        available:
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\DiffCommand'
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\ExecuteCommand'
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\GenerateCommand'
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand'
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\StatusCommand'
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\VersionCommand'
          - 'Craod\Api\Cli\Command\Cache\FlushCommand'
          - 'Craod\Api\Cli\Command\Data\User\InstallCommand'
          - 'Craod\Api\Cli\Command\Fixture\UpCommand'
          - 'Craod\Api\Cli\Command\Fixture\DownCommand'
          - 'Craod\Api\Cli\Command\Fixture\ListCommand'
          - 'Craod\Api\Cli\Command\Search\Index\CreateCommand'
          - 'Craod\Api\Cli\Command\Search\Index\DeleteCommand'
      data:
        userRole:
          - 'administrator'
      fixtures:
        order:
          - 'user'
          - 'category'
        map:
          user: 'Craod\Api\Cli\Fixture\UserFixture'
          category: 'Craod\Api\Cli\Fixture\CategoryFixture'
        settings:
          'Craod\Api\Cli\Fixture\UserFixture':
            usersToCreate: 258
            guidRange: '39f73244-bda8-4105-a1ad-f96a7f9cxxxx'
          'Craod\Api\Cli\Fixture\CategoryFixture':
            usersToCreate: 258
            guidRange: '39f73244-bda8-4105-a1ad-f96a7f9dxxxx'