Craod:
  Api:
    database:
      settings:
        dbname: 'craod'
        user: 'craod'
        password: '123'
        host: 'localhost'
        driver: 'pdo_pgsql'
    doctrine:
      types:
        jsonb: 'Boldtrn\JsonbBundle\Types\JsonbArrayType'
        password: 'Cpliakas\Password\Doctrine\PasswordType'
    rest:
      settings:
        debug: false
    cli:
      commands:
        - 'Doctrine\DBAL\Migrations\Tools\Console\Command\DiffCommand'
        - 'Doctrine\DBAL\Migrations\Tools\Console\Command\ExecuteCommand'
        - 'Doctrine\DBAL\Migrations\Tools\Console\Command\GenerateCommand'
        - 'Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand'
        - 'Doctrine\DBAL\Migrations\Tools\Console\Command\StatusCommand'
        - 'Doctrine\DBAL\Migrations\Tools\Console\Command\VersionCommand'
        - 'Craod\Api\Cli\Command\Cache\FlushCommand'
        - 'Craod\Api\Cli\Command\Data\InstallCommand'
        - 'Craod\Api\Cli\Command\Data\UserRole\InstallCommand'
      data:
        userRole:
          - 'administrator'
        install:
          - 'userrole'
      fixtures:
        order:
          - 'userRole'
          - 'user'
        map:
          userRole: 'Craod\Api\Cli\Fixture\UserRoleFixture'
          user: 'Craod\Api\Cli\Fixture\UserFixture'