Craod:
  Api:
    database:
      settings:
        dbname: 'craod'
        user: 'craod'
        password: '123'
        host: 'localhost'
        port: 5432
        driver: 'pdo_pgsql'
    elasticSearch:
      indexer:
        path: "Data/Indexer/"
      jdbc:
        version: "2.1.0.0"
        path: "../Configuration/elasticsearch-jdbc-2.1.0.0"
    doctrine:
      types:
        jsonb: 'Boldtrn\JsonbBundle\Types\JsonbArrayType'
        password: 'Cpliakas\Password\Doctrine\PasswordType'
      functions:
        string:
          cast: 'Oro\ORM\Query\AST\Functions\Cast'
          get_json_field: 'Opsway\Doctrine\ORM\Query\AST\Functions\GetJsonField'
    annotations:
      settings:
        debug: true
    user:
      onlineThreshold: '-5 minutes'
    rest:
      settings:
        debug: false
        exposed:
          one: 'two'
    cli:
      commands:
        available:
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\DiffCommand'
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\ExecuteCommand'
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\GenerateCommand'
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\MigrateCommand'
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\StatusCommand'
          - 'Doctrine\DBAL\Migrations\Tools\Console\Command\VersionCommand'
          - 'Craod\Api\Cli\Command\Cache\FlushCommand'
          - 'Craod\Api\Cli\Command\Data\User\InstallCommand'
          - 'Craod\Api\Cli\Command\Fixture\UpCommand'
          - 'Craod\Api\Cli\Command\Fixture\DownCommand'
          - 'Craod\Api\Cli\Command\Fixture\ListCommand'
          - 'Craod\Api\Cli\Command\Search\IndexCommand'
      data:
        userRole:
          - 'administrator'
      fixtures:
        order:
          - 'user'
        map:
          user: 'Craod\Api\Cli\Fixture\UserFixture'
        settings:
          'Craod\Api\Cli\Fixture\UserFixture':
            usersToCreate: 258
            guidRange: '39f73244-bda8-4105-a1ad-f96a7f9cxxxx'