Craod:
  Api:
    rest:
      settings:
        mode: 'production'
        debug: false
        exposed:
          context: 'production'
          storage:
            location: 'https://craod-public.s3.amazonaws.com/production'
    storage:
      cloudFront:
        domain: 'd3sngbj3s4qh90.cloudfront.net'
        keyPair: 'APKAJFJIAQDKXYCC6FQQ'